/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTahunAjaranIndexRouteImport } from './routes/_authenticated/tahun-ajaran/index'
import { Route as AuthenticatedSppIndexRouteImport } from './routes/_authenticated/spp/index'
import { Route as AuthenticatedSiswaIndexRouteImport } from './routes/_authenticated/siswa/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedPpdbIndexRouteImport } from './routes/_authenticated/ppdb/index'
import { Route as AuthenticatedKeuanganIndexRouteImport } from './routes/_authenticated/keuangan/index'
import { Route as AuthenticatedKelasIndexRouteImport } from './routes/_authenticated/kelas/index'
import { Route as AuthenticatedKalenderIndexRouteImport } from './routes/_authenticated/kalender/index'
import { Route as AuthenticatedGuruIndexRouteImport } from './routes/_authenticated/guru/index'
import { Route as AuthenticatedAlumniIndexRouteImport } from './routes/_authenticated/alumni/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedSppLaporanRouteImport } from './routes/_authenticated/spp/laporan'
import { Route as AuthenticatedSppJenisBayarRouteImport } from './routes/_authenticated/spp/jenis-bayar'
import { Route as AuthenticatedSppDiskonRouteImport } from './routes/_authenticated/spp/diskon'
import { Route as AuthenticatedSppStudentIdRouteImport } from './routes/_authenticated/spp/$studentId'
import { Route as AuthenticatedSiswaIdRouteImport } from './routes/_authenticated/siswa/$id'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedPpdbIdRouteImport } from './routes/_authenticated/ppdb/$id'
import { Route as AuthenticatedKeuanganLaporanRouteImport } from './routes/_authenticated/keuangan/laporan'
import { Route as AuthenticatedKeuanganKategoriRouteImport } from './routes/_authenticated/keuangan/kategori'
import { Route as AuthenticatedKeuanganArusKasRouteImport } from './routes/_authenticated/keuangan/arus-kas'
import { Route as AuthenticatedKeuanganAkunRouteImport } from './routes/_authenticated/keuangan/akun'
import { Route as AuthenticatedGuruPerformaRouteImport } from './routes/_authenticated/guru/performa'
import { Route as AuthenticatedGuruPenugasanRouteImport } from './routes/_authenticated/guru/penugasan'
import { Route as AuthenticatedGuruIdRouteImport } from './routes/_authenticated/guru/$id'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTahunAjaranIndexRoute =
  AuthenticatedTahunAjaranIndexRouteImport.update({
    id: '/tahun-ajaran/',
    path: '/tahun-ajaran/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSppIndexRoute = AuthenticatedSppIndexRouteImport.update({
  id: '/spp/',
  path: '/spp/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSiswaIndexRoute = AuthenticatedSiswaIndexRouteImport.update({
  id: '/siswa/',
  path: '/siswa/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedPpdbIndexRoute = AuthenticatedPpdbIndexRouteImport.update({
  id: '/ppdb/',
  path: '/ppdb/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKeuanganIndexRoute =
  AuthenticatedKeuanganIndexRouteImport.update({
    id: '/keuangan/',
    path: '/keuangan/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKelasIndexRoute = AuthenticatedKelasIndexRouteImport.update({
  id: '/kelas/',
  path: '/kelas/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKalenderIndexRoute =
  AuthenticatedKalenderIndexRouteImport.update({
    id: '/kalender/',
    path: '/kalender/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGuruIndexRoute = AuthenticatedGuruIndexRouteImport.update({
  id: '/guru/',
  path: '/guru/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlumniIndexRoute =
  AuthenticatedAlumniIndexRouteImport.update({
    id: '/alumni/',
    path: '/alumni/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedSppLaporanRoute = AuthenticatedSppLaporanRouteImport.update({
  id: '/spp/laporan',
  path: '/spp/laporan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSppJenisBayarRoute =
  AuthenticatedSppJenisBayarRouteImport.update({
    id: '/spp/jenis-bayar',
    path: '/spp/jenis-bayar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSppDiskonRoute = AuthenticatedSppDiskonRouteImport.update({
  id: '/spp/diskon',
  path: '/spp/diskon',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSppStudentIdRoute =
  AuthenticatedSppStudentIdRouteImport.update({
    id: '/spp/$studentId',
    path: '/spp/$studentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSiswaIdRoute = AuthenticatedSiswaIdRouteImport.update({
  id: '/siswa/$id',
  path: '/siswa/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedPpdbIdRoute = AuthenticatedPpdbIdRouteImport.update({
  id: '/ppdb/$id',
  path: '/ppdb/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKeuanganLaporanRoute =
  AuthenticatedKeuanganLaporanRouteImport.update({
    id: '/keuangan/laporan',
    path: '/keuangan/laporan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKeuanganKategoriRoute =
  AuthenticatedKeuanganKategoriRouteImport.update({
    id: '/keuangan/kategori',
    path: '/keuangan/kategori',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKeuanganArusKasRoute =
  AuthenticatedKeuanganArusKasRouteImport.update({
    id: '/keuangan/arus-kas',
    path: '/keuangan/arus-kas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKeuanganAkunRoute =
  AuthenticatedKeuanganAkunRouteImport.update({
    id: '/keuangan/akun',
    path: '/keuangan/akun',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGuruPerformaRoute =
  AuthenticatedGuruPerformaRouteImport.update({
    id: '/guru/performa',
    path: '/guru/performa',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGuruPenugasanRoute =
  AuthenticatedGuruPenugasanRouteImport.update({
    id: '/guru/penugasan',
    path: '/guru/penugasan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGuruIdRoute = AuthenticatedGuruIdRouteImport.update({
  id: '/guru/$id',
  path: '/guru/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/guru/$id': typeof AuthenticatedGuruIdRoute
  '/guru/penugasan': typeof AuthenticatedGuruPenugasanRoute
  '/guru/performa': typeof AuthenticatedGuruPerformaRoute
  '/keuangan/akun': typeof AuthenticatedKeuanganAkunRoute
  '/keuangan/arus-kas': typeof AuthenticatedKeuanganArusKasRoute
  '/keuangan/kategori': typeof AuthenticatedKeuanganKategoriRoute
  '/keuangan/laporan': typeof AuthenticatedKeuanganLaporanRoute
  '/ppdb/$id': typeof AuthenticatedPpdbIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/siswa/$id': typeof AuthenticatedSiswaIdRoute
  '/spp/$studentId': typeof AuthenticatedSppStudentIdRoute
  '/spp/diskon': typeof AuthenticatedSppDiskonRoute
  '/spp/jenis-bayar': typeof AuthenticatedSppJenisBayarRoute
  '/spp/laporan': typeof AuthenticatedSppLaporanRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/alumni/': typeof AuthenticatedAlumniIndexRoute
  '/guru/': typeof AuthenticatedGuruIndexRoute
  '/kalender/': typeof AuthenticatedKalenderIndexRoute
  '/kelas/': typeof AuthenticatedKelasIndexRoute
  '/keuangan/': typeof AuthenticatedKeuanganIndexRoute
  '/ppdb/': typeof AuthenticatedPpdbIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/siswa/': typeof AuthenticatedSiswaIndexRoute
  '/spp/': typeof AuthenticatedSppIndexRoute
  '/tahun-ajaran/': typeof AuthenticatedTahunAjaranIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/guru/$id': typeof AuthenticatedGuruIdRoute
  '/guru/penugasan': typeof AuthenticatedGuruPenugasanRoute
  '/guru/performa': typeof AuthenticatedGuruPerformaRoute
  '/keuangan/akun': typeof AuthenticatedKeuanganAkunRoute
  '/keuangan/arus-kas': typeof AuthenticatedKeuanganArusKasRoute
  '/keuangan/kategori': typeof AuthenticatedKeuanganKategoriRoute
  '/keuangan/laporan': typeof AuthenticatedKeuanganLaporanRoute
  '/ppdb/$id': typeof AuthenticatedPpdbIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/siswa/$id': typeof AuthenticatedSiswaIdRoute
  '/spp/$studentId': typeof AuthenticatedSppStudentIdRoute
  '/spp/diskon': typeof AuthenticatedSppDiskonRoute
  '/spp/jenis-bayar': typeof AuthenticatedSppJenisBayarRoute
  '/spp/laporan': typeof AuthenticatedSppLaporanRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/alumni': typeof AuthenticatedAlumniIndexRoute
  '/guru': typeof AuthenticatedGuruIndexRoute
  '/kalender': typeof AuthenticatedKalenderIndexRoute
  '/kelas': typeof AuthenticatedKelasIndexRoute
  '/keuangan': typeof AuthenticatedKeuanganIndexRoute
  '/ppdb': typeof AuthenticatedPpdbIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/siswa': typeof AuthenticatedSiswaIndexRoute
  '/spp': typeof AuthenticatedSppIndexRoute
  '/tahun-ajaran': typeof AuthenticatedTahunAjaranIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/guru/$id': typeof AuthenticatedGuruIdRoute
  '/_authenticated/guru/penugasan': typeof AuthenticatedGuruPenugasanRoute
  '/_authenticated/guru/performa': typeof AuthenticatedGuruPerformaRoute
  '/_authenticated/keuangan/akun': typeof AuthenticatedKeuanganAkunRoute
  '/_authenticated/keuangan/arus-kas': typeof AuthenticatedKeuanganArusKasRoute
  '/_authenticated/keuangan/kategori': typeof AuthenticatedKeuanganKategoriRoute
  '/_authenticated/keuangan/laporan': typeof AuthenticatedKeuanganLaporanRoute
  '/_authenticated/ppdb/$id': typeof AuthenticatedPpdbIdRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/siswa/$id': typeof AuthenticatedSiswaIdRoute
  '/_authenticated/spp/$studentId': typeof AuthenticatedSppStudentIdRoute
  '/_authenticated/spp/diskon': typeof AuthenticatedSppDiskonRoute
  '/_authenticated/spp/jenis-bayar': typeof AuthenticatedSppJenisBayarRoute
  '/_authenticated/spp/laporan': typeof AuthenticatedSppLaporanRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/alumni/': typeof AuthenticatedAlumniIndexRoute
  '/_authenticated/guru/': typeof AuthenticatedGuruIndexRoute
  '/_authenticated/kalender/': typeof AuthenticatedKalenderIndexRoute
  '/_authenticated/kelas/': typeof AuthenticatedKelasIndexRoute
  '/_authenticated/keuangan/': typeof AuthenticatedKeuanganIndexRoute
  '/_authenticated/ppdb/': typeof AuthenticatedPpdbIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/siswa/': typeof AuthenticatedSiswaIndexRoute
  '/_authenticated/spp/': typeof AuthenticatedSppIndexRoute
  '/_authenticated/tahun-ajaran/': typeof AuthenticatedTahunAjaranIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clerk'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/errors/$error'
    | '/guru/$id'
    | '/guru/penugasan'
    | '/guru/performa'
    | '/keuangan/akun'
    | '/keuangan/arus-kas'
    | '/keuangan/kategori'
    | '/keuangan/laporan'
    | '/ppdb/$id'
    | '/settings/account'
    | '/settings/appearance'
    | '/siswa/$id'
    | '/spp/$studentId'
    | '/spp/diskon'
    | '/spp/jenis-bayar'
    | '/spp/laporan'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/alumni/'
    | '/guru/'
    | '/kalender/'
    | '/kelas/'
    | '/keuangan/'
    | '/ppdb/'
    | '/settings/'
    | '/siswa/'
    | '/spp/'
    | '/tahun-ajaran/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/guru/$id'
    | '/guru/penugasan'
    | '/guru/performa'
    | '/keuangan/akun'
    | '/keuangan/arus-kas'
    | '/keuangan/kategori'
    | '/keuangan/laporan'
    | '/ppdb/$id'
    | '/settings/account'
    | '/settings/appearance'
    | '/siswa/$id'
    | '/spp/$studentId'
    | '/spp/diskon'
    | '/spp/jenis-bayar'
    | '/spp/laporan'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/alumni'
    | '/guru'
    | '/kalender'
    | '/kelas'
    | '/keuangan'
    | '/ppdb'
    | '/settings'
    | '/siswa'
    | '/spp'
    | '/tahun-ajaran'
    | '/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/guru/$id'
    | '/_authenticated/guru/penugasan'
    | '/_authenticated/guru/performa'
    | '/_authenticated/keuangan/akun'
    | '/_authenticated/keuangan/arus-kas'
    | '/_authenticated/keuangan/kategori'
    | '/_authenticated/keuangan/laporan'
    | '/_authenticated/ppdb/$id'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/siswa/$id'
    | '/_authenticated/spp/$studentId'
    | '/_authenticated/spp/diskon'
    | '/_authenticated/spp/jenis-bayar'
    | '/_authenticated/spp/laporan'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/alumni/'
    | '/_authenticated/guru/'
    | '/_authenticated/kalender/'
    | '/_authenticated/kelas/'
    | '/_authenticated/keuangan/'
    | '/_authenticated/ppdb/'
    | '/_authenticated/settings/'
    | '/_authenticated/siswa/'
    | '/_authenticated/spp/'
    | '/_authenticated/tahun-ajaran/'
    | '/_authenticated/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tahun-ajaran/': {
      id: '/_authenticated/tahun-ajaran/'
      path: '/tahun-ajaran'
      fullPath: '/tahun-ajaran/'
      preLoaderRoute: typeof AuthenticatedTahunAjaranIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/spp/': {
      id: '/_authenticated/spp/'
      path: '/spp'
      fullPath: '/spp/'
      preLoaderRoute: typeof AuthenticatedSppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/siswa/': {
      id: '/_authenticated/siswa/'
      path: '/siswa'
      fullPath: '/siswa/'
      preLoaderRoute: typeof AuthenticatedSiswaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/ppdb/': {
      id: '/_authenticated/ppdb/'
      path: '/ppdb'
      fullPath: '/ppdb/'
      preLoaderRoute: typeof AuthenticatedPpdbIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/keuangan/': {
      id: '/_authenticated/keuangan/'
      path: '/keuangan'
      fullPath: '/keuangan/'
      preLoaderRoute: typeof AuthenticatedKeuanganIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kelas/': {
      id: '/_authenticated/kelas/'
      path: '/kelas'
      fullPath: '/kelas/'
      preLoaderRoute: typeof AuthenticatedKelasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kalender/': {
      id: '/_authenticated/kalender/'
      path: '/kalender'
      fullPath: '/kalender/'
      preLoaderRoute: typeof AuthenticatedKalenderIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guru/': {
      id: '/_authenticated/guru/'
      path: '/guru'
      fullPath: '/guru/'
      preLoaderRoute: typeof AuthenticatedGuruIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alumni/': {
      id: '/_authenticated/alumni/'
      path: '/alumni'
      fullPath: '/alumni/'
      preLoaderRoute: typeof AuthenticatedAlumniIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/spp/laporan': {
      id: '/_authenticated/spp/laporan'
      path: '/spp/laporan'
      fullPath: '/spp/laporan'
      preLoaderRoute: typeof AuthenticatedSppLaporanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/spp/jenis-bayar': {
      id: '/_authenticated/spp/jenis-bayar'
      path: '/spp/jenis-bayar'
      fullPath: '/spp/jenis-bayar'
      preLoaderRoute: typeof AuthenticatedSppJenisBayarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/spp/diskon': {
      id: '/_authenticated/spp/diskon'
      path: '/spp/diskon'
      fullPath: '/spp/diskon'
      preLoaderRoute: typeof AuthenticatedSppDiskonRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/spp/$studentId': {
      id: '/_authenticated/spp/$studentId'
      path: '/spp/$studentId'
      fullPath: '/spp/$studentId'
      preLoaderRoute: typeof AuthenticatedSppStudentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/siswa/$id': {
      id: '/_authenticated/siswa/$id'
      path: '/siswa/$id'
      fullPath: '/siswa/$id'
      preLoaderRoute: typeof AuthenticatedSiswaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/ppdb/$id': {
      id: '/_authenticated/ppdb/$id'
      path: '/ppdb/$id'
      fullPath: '/ppdb/$id'
      preLoaderRoute: typeof AuthenticatedPpdbIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/keuangan/laporan': {
      id: '/_authenticated/keuangan/laporan'
      path: '/keuangan/laporan'
      fullPath: '/keuangan/laporan'
      preLoaderRoute: typeof AuthenticatedKeuanganLaporanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/keuangan/kategori': {
      id: '/_authenticated/keuangan/kategori'
      path: '/keuangan/kategori'
      fullPath: '/keuangan/kategori'
      preLoaderRoute: typeof AuthenticatedKeuanganKategoriRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/keuangan/arus-kas': {
      id: '/_authenticated/keuangan/arus-kas'
      path: '/keuangan/arus-kas'
      fullPath: '/keuangan/arus-kas'
      preLoaderRoute: typeof AuthenticatedKeuanganArusKasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/keuangan/akun': {
      id: '/_authenticated/keuangan/akun'
      path: '/keuangan/akun'
      fullPath: '/keuangan/akun'
      preLoaderRoute: typeof AuthenticatedKeuanganAkunRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guru/performa': {
      id: '/_authenticated/guru/performa'
      path: '/guru/performa'
      fullPath: '/guru/performa'
      preLoaderRoute: typeof AuthenticatedGuruPerformaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guru/penugasan': {
      id: '/_authenticated/guru/penugasan'
      path: '/guru/penugasan'
      fullPath: '/guru/penugasan'
      preLoaderRoute: typeof AuthenticatedGuruPenugasanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guru/$id': {
      id: '/_authenticated/guru/$id'
      path: '/guru/$id'
      fullPath: '/guru/$id'
      preLoaderRoute: typeof AuthenticatedGuruIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedGuruIdRoute: typeof AuthenticatedGuruIdRoute
  AuthenticatedGuruPenugasanRoute: typeof AuthenticatedGuruPenugasanRoute
  AuthenticatedGuruPerformaRoute: typeof AuthenticatedGuruPerformaRoute
  AuthenticatedKeuanganAkunRoute: typeof AuthenticatedKeuanganAkunRoute
  AuthenticatedKeuanganArusKasRoute: typeof AuthenticatedKeuanganArusKasRoute
  AuthenticatedKeuanganKategoriRoute: typeof AuthenticatedKeuanganKategoriRoute
  AuthenticatedKeuanganLaporanRoute: typeof AuthenticatedKeuanganLaporanRoute
  AuthenticatedPpdbIdRoute: typeof AuthenticatedPpdbIdRoute
  AuthenticatedSiswaIdRoute: typeof AuthenticatedSiswaIdRoute
  AuthenticatedSppStudentIdRoute: typeof AuthenticatedSppStudentIdRoute
  AuthenticatedSppDiskonRoute: typeof AuthenticatedSppDiskonRoute
  AuthenticatedSppJenisBayarRoute: typeof AuthenticatedSppJenisBayarRoute
  AuthenticatedSppLaporanRoute: typeof AuthenticatedSppLaporanRoute
  AuthenticatedAlumniIndexRoute: typeof AuthenticatedAlumniIndexRoute
  AuthenticatedGuruIndexRoute: typeof AuthenticatedGuruIndexRoute
  AuthenticatedKalenderIndexRoute: typeof AuthenticatedKalenderIndexRoute
  AuthenticatedKelasIndexRoute: typeof AuthenticatedKelasIndexRoute
  AuthenticatedKeuanganIndexRoute: typeof AuthenticatedKeuanganIndexRoute
  AuthenticatedPpdbIndexRoute: typeof AuthenticatedPpdbIndexRoute
  AuthenticatedSiswaIndexRoute: typeof AuthenticatedSiswaIndexRoute
  AuthenticatedSppIndexRoute: typeof AuthenticatedSppIndexRoute
  AuthenticatedTahunAjaranIndexRoute: typeof AuthenticatedTahunAjaranIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedGuruIdRoute: AuthenticatedGuruIdRoute,
  AuthenticatedGuruPenugasanRoute: AuthenticatedGuruPenugasanRoute,
  AuthenticatedGuruPerformaRoute: AuthenticatedGuruPerformaRoute,
  AuthenticatedKeuanganAkunRoute: AuthenticatedKeuanganAkunRoute,
  AuthenticatedKeuanganArusKasRoute: AuthenticatedKeuanganArusKasRoute,
  AuthenticatedKeuanganKategoriRoute: AuthenticatedKeuanganKategoriRoute,
  AuthenticatedKeuanganLaporanRoute: AuthenticatedKeuanganLaporanRoute,
  AuthenticatedPpdbIdRoute: AuthenticatedPpdbIdRoute,
  AuthenticatedSiswaIdRoute: AuthenticatedSiswaIdRoute,
  AuthenticatedSppStudentIdRoute: AuthenticatedSppStudentIdRoute,
  AuthenticatedSppDiskonRoute: AuthenticatedSppDiskonRoute,
  AuthenticatedSppJenisBayarRoute: AuthenticatedSppJenisBayarRoute,
  AuthenticatedSppLaporanRoute: AuthenticatedSppLaporanRoute,
  AuthenticatedAlumniIndexRoute: AuthenticatedAlumniIndexRoute,
  AuthenticatedGuruIndexRoute: AuthenticatedGuruIndexRoute,
  AuthenticatedKalenderIndexRoute: AuthenticatedKalenderIndexRoute,
  AuthenticatedKelasIndexRoute: AuthenticatedKelasIndexRoute,
  AuthenticatedKeuanganIndexRoute: AuthenticatedKeuanganIndexRoute,
  AuthenticatedPpdbIndexRoute: AuthenticatedPpdbIndexRoute,
  AuthenticatedSiswaIndexRoute: AuthenticatedSiswaIndexRoute,
  AuthenticatedSppIndexRoute: AuthenticatedSppIndexRoute,
  AuthenticatedTahunAjaranIndexRoute: AuthenticatedTahunAjaranIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
